[package]
name = "fibril"
license = "MIT"
version = "0.0.0"
edition = "2021"
authors = ["Jonathan Nadal <jon.nadal@gmail.com>"]

[dependencies]
corosensei = "0.1"
fibril_core = { path = "../core" }

[features]
serde = ["fibril_core/serde"]
