[package]
name = "fibril_core"
license = "MIT OR Apache-2.0"
version = "0.0.0"
edition = "2021"
authors = ["Jonathan Nadal <jon.nadal@gmail.com>"]
description = "Core types for the Fibril library."

[dependencies.serde]
optional = true
version = "1"
features = ["derive"]
